on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Build Windows
jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Compile
        run: "mkdir build && cd build && cmake .. && cmake --build . --config Release"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Release
          path: build/Release/saucer.exe
